site_name: Arilekh Report
site_description: Modern .NET Reporting Engine
site_author: Siva V

repo_url: https://github.com/siva7170/arilekh-report
repo_name: siva7170/arilekh-report

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Report Designer: report-designer.md
  - Report Generation: report-generation.md
  - Report Viewer: report-viewer.md
  - Expressions: expressions.md
  - Charts: charts.md
  - API Reference: api-reference.md
  - Examples: examples.md
  - FAQ: faq.md