using ArilekhReport.Core;
using ArilekhReport.Core.Rendering;
using Microsoft.AspNetCore.Mvc;
using ArilekhReport.Core;
using ArilekhReport.Core.Data;
using ArilekhReport.WebApi.Services;
using ArilekhReport.WebApi.DTOs;

namespace ArilekhReport.WebApi.Controllers;

/// <summary>
/// Report Viewer API.
///
/// POST   /api/reports/render                 — render report, get session GUID
/// GET    /api/reports/{id}/info              — total pages, dimensions
/// GET    /api/reports/{id}/pages/{n}         — single page elements (lazy)
/// GET    /api/reports/{id}/pages             — range of pages ?from=1&to=10
/// GET    /api/reports/{id}/thumbnails        — page list with first-text labels
/// GET    /api/reports/{id}/search?q=...      — full-text search across all pages
/// DELETE /api/reports/{id}                   — release session early
/// </summary>
[ApiController]
[Route("api/reports")]
public sealed class ReportsController : ControllerBase
{
    private readonly ReportSessionService _sessions;
    private readonly IWebHostEnvironment _env;
    public ReportsController(ReportSessionService sessions, IWebHostEnvironment env)
    {
        _env = env;
        _sessions = sessions;
    }
      

    // ── POST /api/reports/render ───────────────────────────────────────────────

    /// <summary>
    /// Render a report from .rdx XML + data, return a session GUID.
    /// Angular posts this once and then loads pages lazily.
    /// </summary>
    [HttpPost("render")]
    public async Task<ActionResult<RenderResponse>> Render(
        [FromBody] RenderRequest req,
        CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(req.ReportXml))
            return BadRequest("ReportXml is required.");

        try
        {
            var (id, doc, ms) = await _sessions.RenderAsync(
                req.ReportXml, req.Data, req.Parameters, req.TtlMinutes, ct);

            return Ok(new RenderResponse
            {
                SessionId   = id,
                PageCount   = doc.PageCount,
                PageWidthPt = doc.Pages.Count > 0 ? doc.Pages[0].Width  : 595f,
                PageHeightPt= doc.Pages.Count > 0 ? doc.Pages[0].Height : 842f,
                RenderedAt  = doc.RenderedAt,
                RenderMs    = ms,
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    // ── POST /api/reports/render-server ───────────────────────────────────────

    /// <summary>
    /// Server-side render: the API controller (or your own service) assembles
    /// the DataTables from a database query and calls this endpoint internally.
    /// Angular only needs the session GUID that comes back — it never sees the data.
    ///
    /// Use case: form submission → your controller loads DB data → calls
    /// _sessions.RenderWithTablesAsync(...) → returns GUID → Angular viewer loads pages.
    ///
    /// From Angular you still call GET /pages/{n} as normal.
    /// </summary>
    [HttpPost("render-server")]
    public async Task<ActionResult<RenderResponse>> RenderServer(
        [FromBody] ServerRenderRequest req,
        CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(req.ReportXml))
            return BadRequest("ReportXml is required.");
        if (string.IsNullOrWhiteSpace(req.DataProviderKey))
            return BadRequest("DataProviderKey is required — register an IServerDataProvider.");

        try
        {
            // Look up a registered server-side data provider by key
            var provider = _sessions.GetServerDataProvider(req.DataProviderKey);
            if (provider is null)
                return BadRequest(new { error = $"No server data provider registered for key '{req.DataProviderKey}'." });

            var (id, doc, ms) = await _sessions.RenderWithProviderAsync(
                req.ReportXml, provider, req.Parameters ?? [], req.TtlMinutes, ct);

            return Ok(new RenderResponse
            {
                SessionId    = id,
                PageCount    = doc.PageCount,
                PageWidthPt  = doc.Pages.Count > 0 ? doc.Pages[0].Width  : 595f,
                PageHeightPt = doc.Pages.Count > 0 ? doc.Pages[0].Height : 842f,
                RenderedAt   = doc.RenderedAt,
                RenderMs     = ms,
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    // ── POST /api/reports/load-session ────────────────────────────────────────

    /// <summary>
    /// Accepts a pre-rendered session GUID generated by server code
    /// (e.g. your own microservice called _sessions.RenderAsync directly).
    /// Angular calls this to verify the session exists and get page count.
    /// </summary>
    [HttpGet("{id}/info")]
    public ActionResult<RenderResponse> Info(string id)
    {
        var doc = _sessions.GetDocument(id);
        if (doc is null) return NotFound(new { error = "Session not found or expired." });

        return Ok(new RenderResponse
        {
            SessionId    = id,
            PageCount    = doc.PageCount,
            PageWidthPt  = doc.Pages.Count > 0 ? doc.Pages[0].Width  : 595f,
            PageHeightPt = doc.Pages.Count > 0 ? doc.Pages[0].Height : 842f,
            RenderedAt   = doc.RenderedAt,
        });
    }

    // ── GET /api/reports/{id}/pages/{n} ───────────────────────────────────────

    /// <summary>Returns the elements for a single page. Lightweight — called lazily.</summary>
    [HttpGet("{id}/pages/{pageNumber:int}")]
    public ActionResult<PageResponse> GetPage(string id, int pageNumber)
    {
        var doc  = _sessions.GetDocument(id);
        if (doc is null) return NotFound(new { error = "Session not found or expired." });

        var page = _sessions.GetPage(id, pageNumber);
        if (page is null) return NotFound(new { error = $"Page {pageNumber} not found." });

        return Ok(ElementMapper.ToPageResponse(page, doc.PageCount));
    }

    // ── GET /api/reports/{id}/pages?from=1&to=10 ──────────────────────────────

    /// <summary>Returns a batch of pages — useful for the initial window load.</summary>
    [HttpGet("{id}/pages")]
    public ActionResult<List<PageResponse>> GetPages(
        string id,
        [FromQuery] int from = 1,
        [FromQuery] int to   = 10)
    {
        var doc = _sessions.GetDocument(id);
        if (doc is null) return NotFound();

        from = Math.Max(1, from);
        to   = Math.Min(doc.PageCount, to);

        var result = new List<PageResponse>();
        for (int p = from; p <= to; p++)
        {
            var page = _sessions.GetPage(id, p);
            if (page is not null)
                result.Add(ElementMapper.ToPageResponse(page, doc.PageCount));
        }
        return Ok(result);
    }

    // ── GET /api/reports/{id}/thumbnails ──────────────────────────────────────

    /// <summary>
    /// Returns lightweight page summaries for the left-panel thumbnail list.
    /// Each entry has the page number and the first text string on the page.
    /// </summary>
    [HttpGet("{id}/thumbnails")]
    public ActionResult<ThumbnailListResponse> GetThumbnails(string id)
    {
        var doc = _sessions.GetDocument(id);
        if (doc is null) return NotFound();

        var pages = doc.Pages.Select(p => new PageSummary
        {
            PageNumber = p.PageNumber,
            FirstText  = p.Elements
                          .OfType<RenderedTextElement>()
                          .Select(e => e.Text)
                          .FirstOrDefault(t => !string.IsNullOrWhiteSpace(t)) ?? "",
            GroupLabel = "",   // extended: could extract from group header sections
        }).ToList();

        return Ok(new ThumbnailListResponse
        {
            SessionId = id,
            PageCount = doc.PageCount,
            Pages     = pages,
        });
    }

    // ── GET /api/reports/{id}/search?q=term ───────────────────────────────────

    /// <summary>
    /// Full-text search across all pages.
    /// Returns page numbers + snippet + approximate position of first hit per page.
    /// </summary>
    [HttpGet("{id}/search")]
    public ActionResult<SearchResponse> Search(string id, [FromQuery] string q = "")
    {
        if (string.IsNullOrWhiteSpace(q))
            return BadRequest(new { error = "Query 'q' is required." });

        var doc = _sessions.GetDocument(id);
        if (doc is null) return NotFound();

        var hits = new List<SearchHit>();
        foreach (var page in doc.Pages)
        {
            foreach (var el in page.Elements
                .OfType<RenderedTextElement>())
            {
                if (el.Text.Contains(q, StringComparison.OrdinalIgnoreCase))
                {
                    // Highlight snippet
                    var idx     = el.Text.IndexOf(q, StringComparison.OrdinalIgnoreCase);
                    var start   = Math.Max(0, idx - 20);
                    var snippet = (start > 0 ? "…" : "") +
                                  el.Text.Substring(start, Math.Min(60, el.Text.Length - start)) +
                                  (start + 60 < el.Text.Length ? "…" : "");

                    hits.Add(new SearchHit
                    {
                        PageNumber = page.PageNumber,
                        Snippet    = snippet,
                        X          = el.X,
                        Y          = el.Y,
                    });
                    break; // one hit per page per element is enough for nav
                }
            }
        }

        return Ok(new SearchResponse
        {
            Query   = q,
            Hits    = hits.Count,
            Results = hits,
        });
    }

    public class SalesRequest
    {
        public string Req {  get; set; }
    }

    [HttpPost("generate-sales")]
    public async Task<IActionResult> GenerateSales([FromBody] SalesRequest req)
    {
        var report = XmlReportSerializer.LoadReport(_env.ContentRootPath + Path.DirectorySeparatorChar + "SampleReport" + Path.DirectorySeparatorChar + "SampleReport.rdx");

        var schema = XmlReportSerializer.LoadSchema(_env.ContentRootPath + Path.DirectorySeparatorChar + "SampleReport" + Path.DirectorySeparatorChar + "SampleReport.rds");

        var provider = new DataTableProvider();
        provider.Register(schema.ToSampleDataTable());

        var engine = new ReportEngine();
        var doc = await engine.RenderAsync(report, provider);
        var guid = _sessions.StoreDocument(doc, ttlMinutes: 30);

        return Ok(new { sessionId = guid });
    }

    // ── DELETE /api/reports/{id} ───────────────────────────────────────────────

    [HttpDelete("{id}")]
    public IActionResult Release(string id)
    {
        // Sessions auto-evict; explicit delete just frees memory earlier
        // (We expose RemoveSession from the service for explicit calls)
        return NoContent();
    }
}
