// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReportDesigner.VsExtension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidReportDesignerPackageString = "c8aad8d9-cd73-4d6a-be4c-2540f4432041";
        public static Guid guidReportDesignerPackage = new Guid(guidReportDesignerPackageString);

        public const string guidReportDesignerPackageCmdSetString = "54fbac16-ecb7-43e9-9509-db6b280c39f2";
        public static Guid guidReportDesignerPackageCmdSet = new Guid(guidReportDesignerPackageCmdSetString);

        public const string guidImagesString = "753ca4bc-dc99-4e91-b87d-0a1bb0b417ec";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMainMenuGroup = 0x0601;
        public const int MyMenuGroup = 0x1020;
        public const int SubMenuGroup = 0x1021;
        public const int CtxMenuGroup = 0x1022;
        public const int Command1Id = 0x0100;
        public const int TopLevelMenu = 0x1031;
        public const int Command2Id = 0x0102;
        public const int Command3Id = 0x0103;
        public const int MenuId1 = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
